TestProjet/Models/Categorie.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public int id { get; set; }
        public string nom_categorie { get; set; }
        public string image { get; set; }
        public string description { get; set; }
    }
}

TestProjet/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestProjet.Models;

namespace TestProjet.Controllers
{
    public class CategorieController : Controller
    {

        private EcommerceEntities _db = new EcommerceEntities();

        // GET: Categorie
        public ActionResult Index()
        {
            return View(_db.Categorie.ToList());
        }

        // GET: Categorie/Details/5
        // créer la vue pour les détails
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Categorie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categorie/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Categorie/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Categorie/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Categorie/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Categorie/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TestProjet/Views/Categorie/Index.cshtml
@model IEnumerable<TestProjet.Models.Categorie>

@{
    ViewBag.Title = "Index";
}

blabla
<h2>Catégories</h2>

<div class="cont-cat">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("Liste","Produits", new { id = item.id })">
            <div class="item-cat">
                <h3 class="text-center">@Html.DisplayFor(modelItem => item.nom_categorie)</h3>
                <img src="@Html.DisplayFor(modelItem => item.image)" alt="@Html.DisplayFor(modelItem => item.nom_categorie)" class="img-responsive" />
                <p>
                    @Html.DisplayFor(modelItem => item.description)
                </p>
            </div>
        </a>
    }
</div>


 



   <!--
<h2>Catégories</h2>

<div class="cont-cat">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("Details","Categorie", new { id = item.id })">
            <div class="item-cat">
                <h3 class="text-center">@Html.DisplayFor(modelItem => item.nom_categorie)</h3>
                <img src="@Html.DisplayFor(modelItem => item.image)" alt="@Html.DisplayFor(modelItem => item.nom_categorie)" class="img-responsive" />
                <p id="description_produit">
                    @Html.DisplayFor(modelItem => item.description)
                </p>
            </div>
        </a>
    }
</div>


-->


<!--<h2>Catégories</h2>

<div class="cont-cat">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("Liste","Produits", new { id = item.id })">
            <div class="item-cat">
                <h3 class="text-center">@Html.DisplayFor(modelItem => item.nom_categorie)</h3>
                <img src="@Html.DisplayFor(modelItem => item.image)" alt="@Html.DisplayFor(modelItem => item.nom_categorie)" class="img-responsive" />
                <p>
                    @Html.DisplayFor(modelItem => item.description)
                </p>
            </div>
        </a>
    }
</div>
    -->