TestProjet/Models/Produit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public long id { get; set; }
        public string nom_produit { get; set; }
        public long id_categorie { get; set; }
        public string prix { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public long stock { get; set; }
        public int quantite_lots { get; set; }
        public int niveau_reapprovisionnement { get; set; }
    }
}

TestProjet/Controllers/PaniersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using TestProjet.Models;
using System.Collections;


namespace TestProjet.Controllers

{
    public class PaniersController : Controller
    {
        private EcommerceEntities db = new EcommerceEntities();


        // GET: Paniers
        public ActionResult Index()
        {
            //   Produit prod = new Produit();
            //   ViewBag.monPanier = db.Panier.ToList();
            //   ViewBag.monProduit = db.Produit.ToList();
            //   ViewBag.monProduit2 = db.Produit.All();
            if (User.Identity.Name == "")
            {
                return RedirectToAction("Login", "Account");
            }

            Client c = getClientByMail(User.Identity.Name);
       /*     ViewBag.contenuDuPanier = db.Panier.Where(p => p.id_client == c.id).Join(db.Produit, panier => panier.id_produit, produit => produit.id , (panier, produit ) => new {
                             produitID  = produit.id ,
                             poduitNom = produit.nom_produit ,
                             panierID = panier.id } ).ToList();*/
            var bbb = db.Panier.Where(p => p.id_client == c.id).Join(db.Produit, panier => panier.id_produit, produit => produit.id, (panier, produit) => new {
                produitID = produit.id,
                poduitNom = produit.nom_produit,
                produitImage = produit.image,
                produitPrix = produit.prix,
                panierQTE = panier.quantite,
                panierID = panier.id
            });

            int prixTotal = 0;
            
            ArrayList resultat = new ArrayList();
            foreach (var item in bbb)
            {
                ArrayList monItem = new ArrayList();
                monItem.Add(item.panierID);
                monItem.Add(item.poduitNom);
                monItem.Add(item.produitID);
                monItem.Add(item.produitImage);
                monItem.Add(item.produitPrix);
                monItem.Add(item.panierQTE);
                resultat.Add(monItem);
                prixTotal = prixTotal + (int.Parse(item.produitPrix) * item.panierQTE );
            }

            /*   Array tab
               foreach (var item in bbb)

                   expando.Add( item.panierID.ToString(), item);*/
            ViewBag.prixPanier = prixTotal;
            ViewBag.contenuDuPanier = resultat;

            /*var a = (from p in db.Produit join pa in db.Panier on p.id equals pa.id_produit where pa.id_client == c.id
                     select p
                );*/
            return View(db.Panier.ToList());
        }

        //Ajout d'un panier
        public ActionResult AddPanier(int quantite, int id_produit, int IdPage)
        {
            if (User.Identity.Name == "")
            {
                return RedirectToAction("Login", "Account");
            }

            Client c = getClientByMail(User.Identity.Name);

            Panier myNewPane = new Panier();
            Panier panier = new Panier();
            //panier = db.Panier.Where(i => i.id_produit == 1);
            

            myNewPane.id_client = c.id;
            myNewPane.id_produit = id_produit;
            myNewPane.quantite = quantite;

            db.Panier.Add(myNewPane);
            db.SaveChanges();

            return RedirectToAction("Liste", "Produits", new { id = IdPage });
        }

        // GET: Paniers/Details/5
     /*   public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Panier panier = db.Panier.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            return View(panier);
        }*/

        // GET: Paniers/Create
     /*   public ActionResult Create()
        { 
            return View();
        }*/

        // POST: Paniers/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
    /*    [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,id_client,id_produit,quantite")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                db.Panier.Add(panier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(panier);
        }*/

        // GET: Paniers/Edit/5
      /*  public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Panier panier = db.Panier.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            return View(panier);
        }*/

        // POST: Paniers/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
    /*    [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,id_client,id_produit,quantite")] Panier panier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(panier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(panier);
        }*/

        // GET: Paniers/Delete/5
  /*      public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Panier panier = db.Panier.Find(id);
            if (panier == null)
            {
                return HttpNotFound();
            }
            return View(panier);
        }*/

        // POST: Paniers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Panier panier = db.Panier.Find(id);
            db.Panier.Remove(panier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        private Client getClientByMail(string mail)
        {
            return db.Client.Where(c => c.email == mail).First();
        }


        public ActionResult DeleteFromPanier(string id_produit)
        {
            long id = long.Parse(id_produit);
            db.Panier.Remove(db.Panier.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestProjet/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestProjet.Models;

namespace TestProjet.Controllers
{
    public class ProduitsController : Controller
    {
        private EcommerceEntities db = new EcommerceEntities();

        // GET: Produits
        public ActionResult Index()
        {
            return View(db.Produit.ToList());
        }
        // GET: Produits/Gestion
        public ActionResult Gestion()
        {
            return View(db.Produit.ToList());
        }

        // GET: Produits/categorie/5
        public ActionResult Liste(long? id)
        {
            /* if (id_categorie == null)
             {
                 return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
             }*/
            //string expression;
            //expression = "id_categorie = " + id_categorie;
            //Produit produit = db.Produit.Select(expression);
            /* if (produit == null)
            {
                return HttpNotFound();
            }*/
            //return View(db.Produit.ToList());
            Categorie cat = new Categorie();
            cat = db.Categorie.Find(id);
            ViewBag.idPage = id;
            ViewBag.idPageName = cat.nom_categorie;
            return View(db.Produit.Where(i => i.id_categorie == id));
        }

        // GET: Produits/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produit.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            Categorie cat = new Categorie();
            cat = db.Categorie.Find(produit.id_categorie);
            ViewBag.idPageName = cat.nom_categorie;
            return View(produit);
        }

        // GET: Produits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produits/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nom_produit,id_categorie,prix,image,description,stock,quantite_lots,niveau_reapprovisionnement")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Produit.Add(produit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produit);
        }

        // GET: Produits/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produit.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: Produits/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nom_produit,id_categorie,prix,image,description,stock,quantite_lots,niveau_reapprovisionnement")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produit);
        }

        // GET: Produits/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produit.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Produit produit = db.Produit.Find(id);
            db.Produit.Remove(produit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestProjet/Views/Produits/Create.cshtml
@model TestProjet.Models.Produit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom_produit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_produit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_produit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_categorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_categorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_categorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantite_lots, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantite_lots, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantite_lots, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.niveau_reapprovisionnement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.niveau_reapprovisionnement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.niveau_reapprovisionnement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<p>
    @Html.ActionLink("Retour", "index", "Categorie")
</p>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestProjet/Views/Produits/Delete.cshtml
@model TestProjet.Models.Produit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_produit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_produit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_categorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_categorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantite_lots)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantite_lots)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.niveau_reapprovisionnement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.niveau_reapprovisionnement)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p>
            @Html.ActionLink("Retour", "index", "Categorie")
        </p>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestProjet/Views/Produits/Details.cshtml
@model TestProjet.Models.Produit

@{
    ViewBag.Title = "Details";
}
<br />
<br />
<div class="navigationBarre">
    <a class="navigationBarre" href="@Url.Action("index","Home")">Home</a> / <a class="navigationBarre" href="@Url.Action("Liste","Produits", new { id = Model.id_categorie })">@ViewBag.idPageName</a> / @Html.DisplayFor(model => model.nom_produit)
</div>
<br />
<br />

<h2>Details - @Html.DisplayFor(model => model.nom_produit)</h2>
<div class="row">
    <div id="image_produits_detail" class=".col-md-4">
        <img src="@Html.DisplayFor(model => model.image)" alt="@Html.DisplayFor(model => model.nom_produit)" class="image_detail" />
    </div>


    <dl class="dl-horizontal .col-md-8 info_detail">
        <dt>
            Nom :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_produit)
        </dd>

        <dt>
            Prix :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix)
        </dd>

        <dt>
            Description :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            En stock :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stock)
        </dd>

    </dl>
    <br />
    <br />
    <div class="addPane--button right">
        @using (Html.BeginForm("AddPanier", "Paniers"))
        {
            <input class="bouton" type="submit" value="Ajouter au panier" />
                        <input name="quantite" class="qte" value="1" />
                        <input name="id_produit" class="id" value="@Html.DisplayFor(model => model.id)" style="display:none;"  />
                        <input name="IdPage" class="IdPage" value="@Html.DisplayFor(model => model.id_categorie)"  style="display:none;"/>
        }
    </div>
</div>

<p>
    <!--    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |-->
    @Html.ActionLink("retour", "Liste", new { id = Model.id_categorie }, new { @class = "right" })
</p>

TestProjet/Views/Produits/Edit.cshtml
@model TestProjet.Models.Produit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nom_produit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_produit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_produit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_categorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_categorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_categorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantite_lots, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantite_lots, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantite_lots, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.niveau_reapprovisionnement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.niveau_reapprovisionnement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.niveau_reapprovisionnement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestProjet/Views/Produits/Gestion.cshtml
@model IEnumerable<TestProjet.Models.Produit>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("retours index", "index")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_produit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.id_categorie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.stock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.quantite_lots)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.niveau_reapprovisionnement)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nom_produit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.id_categorie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantite_lots)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.niveau_reapprovisionnement)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

TestProjet/Views/Produits/Liste.cshtml
@model IEnumerable<TestProjet.Models.Produit>

@{
    ViewBag.Title = "Index";
}
<br /><br />
    <div class="navigationBarre"> 
        <a class="navigationBarre" href="@Url.Action("index","Home")">Home</a> / @ViewBag.idPageName   
    </div>
<br/><br/>
<div class="cont-cat">
    @foreach (var item in Model)
    {
        <div class="item-cat">
            <div class="product--detail">
                <a href="@Url.Action("Details","Produits", new { id = item.id })">
                    <div>
                        <h3 class="text-center">@Html.DisplayFor(modelItem => item.nom_produit)</h3>
                        <img src="@Html.DisplayFor(modelItem => item.image)" alt="@Html.DisplayFor(modelItem => item.nom_produit)" class="img-responsive image_produits_detail" />
                        <div class="details">
                            <div id="description_produit">
                                @Html.DisplayFor(modelItem => item.description)
                            </div>
                            <div class="item-box">
                                Prix : @Html.DisplayFor(modelItem => item.prix) : &euro;
                            </div>
                        </div>
                    </div>
                </a>
                <div class="addPane--button">
                    @using (Html.BeginForm("AddPanier", "Paniers"))
                    {
                        <input class="bouton" type="submit" value="Ajouter au panier" />
                        <input name="quantite" class="qte" value="1" />
                        <input name="id_produit" class="id" value="@item.id" style="visibility: hidden;" />
                        <input name="IdPage" class="IdPage" value="@ViewBag.idPage" style="visibility: hidden;" />
                    }
                </div>
            </div>
        </div>
    }
</div>
<p class="right">
    @Html.ActionLink("Retour", "index", "Home")
</p>
<br />
<br />

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}